final_edu_project/travel_service/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Travel Service API",
        default_version="v1",
        description="Travel Service where you can booking one or several places in different directories, "
        "dates and time.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@busby.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("directions/", views.GetDirectionInfoView.as_view()),
    path("dateroutes/", views.GetDateRouteInfoView.as_view()),
    path("timetrips/", views.GetTimeTripInfoView.as_view()),
    path(
        "info/<slug:direction_slug>/<date_route>/",
        views.DirectionDateRouteView.as_view(),
    ),
    path("filter-timetrips/", views.GetTimeTripInfoFilterView.as_view()),
    path("search-timetrips/", views.GetTimeTripInfoSearchView.as_view()),
    path("order-timetrips/", views.GetTimeTripInfoOrderView.as_view()),
]

final_edu_project/travel_service/booking/urls.py
from django.urls import path

from . import views

app_name = "booking"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "<slug:direction_slug>/<date_route>/", views.get_daytime_trip, name="direction"
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/success",
        views.booking_success,
        name="trip-success",
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/impossible",
        views.booking_impossible,
        name="trip-impossible",
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/",
        views.TripCreateView.as_view(),
        name="trip",
    ),
    path("contacts", views.contacts, name="contacts"),
    path(
        "account/trip/remove/<int:trip_id>/",
        views.trip_remove_in_account,
        name="trip_remove",
    ),
    path("account", views.account, name="account"),
    path("history", views.trips_history, name="trips-history"),
]

final_edu_project/travel_service/travel_service/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_edu_project/travel_service/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import forms, views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            next_page="booking:index", template_name="users/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="booking:index"),
        name="logout",
    ),
    path(
        "change-pass/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy(
                "users:password_change_done"
            ),  # Куда буду перенаправлен после успешной смены пароля,
            # можно перенаправить и на главную страницу. Указан стандартный, переопределил из-за app_name = 'users'.
            template_name="users/password_change.html",  # шаблон, использующейся для отображения
            form_class=forms.CustomPasswordChangeForm,
        ),  # форма, которая передается в шаблон
        name="change",
    ),
    path(
        "change-pass-confirm/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_success.html"
        ),
        name="password_change_done",
    ),
    path(
        "password-reset",
        auth_views.PasswordResetView.as_view(
            email_template_name="users/password_reset_mail.html",
            template_name="users/password_reset.html",
            success_url=reverse_lazy("users:pass-reset-done"),
        ),
        name="pass-reset",
    ),
    path(
        "password-reset-done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="pass-reset-done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("users:reset_complete"),
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="reset_complete",
    ),
    path("info-edit", views.user_edit, name="user-info-edit"),
]

final_edu_project/travel_service/booking/forms.py
from django import forms

from .models import Trip


class TripModelForm(forms.ModelForm):
    """Форма для модели Trip"""

    def __init__(self, *args, **kwargs):
        """Изменение параметров формы при инициализации"""

        super().__init__(*args, **kwargs)
        # Должно было поменять пустое поле в выборе остановки на "Остановка не выбрана"
        self.fields["landing_place"].empty_label = "Остановка не выбрана"

    class Meta:
        model = Trip
        fields = ["number_of_reserved_places", "landing_place", "user_comment"]
        widgets = {
            "number_of_reserved_places": forms.NumberInput(
                attrs={"class": "booking__form-input booking__form-input__num"}
            ),
            "landing_place": forms.Select(attrs={"class": "booking__form-input"}),
            "user_comment": forms.Textarea(
                attrs={"class": "booking__form-input booking__form-input__area"}
            ),
        }
        labels = {
            "number_of_reserved_places": "Кол-во забронированных мест",
            "landing_place": "Остановка",
            "user_comment": "Комментарий",
        }

final_edu_project/travel_service/booking/views.py
import datetime
import os
from typing import Any

import pdfkit
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.core.files.base import File
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template
from django.urls import reverse
from django.views.generic import CreateView

from .forms import TripModelForm
from .models import Direction, Trip
from .tasks import send_tripticket_task
from .utils import decorator_log


# Create your views here.
@decorator_log
def index(request: HttpRequest) -> HttpRequest:
    """Функция предназначена для перехода к странице со списком направлений"""

    directions = Direction.objects.filter(is_active=True).all()
    today = str(
        datetime.datetime(2023, 4, 6).date()
    )  # for debug - указываем определенный день, чтобы записи в бд
    # не создавать каждый раз
    # today = datetime.datetime.now().date()
    return render(
        request,
        "booking/index.html",
        context={"directions": directions, "today": today},
    )


@decorator_log
def get_daytime_trip(
    request: HttpRequest, direction_slug: str, date_route: datetime
) -> HttpRequest:
    """Функция предназначена для перехода к странице со списком дней в которые имеются поездки по данному направлению.
    При выборе определенной даты, высвечиваются все возможные поездки, по умолчанию при переходе на данную страницу
    выбирается текущий день
    """

    # Получили список всех дат по которым возможна бронь поездки
    direction = get_object_or_404(Direction, slug=direction_slug)
    date_routes = (
        direction.dateroute_set.filter(is_active=True).order_by("date_route").all()
    )  # dateroute в dateroute_set взяли из модели
    # Получили список всех поездок сортированных по времени (с утра до вечера)
    day = get_object_or_404(date_routes, date_route=date_route)
    # timetrip в timetrip_set взяли из модели
    trip_times_all = (
        day.timetrip_set.filter(direction=direction).order_by("departure_time").all()
    )
    trip_times_active = (
        day.timetrip_set.filter(direction=direction, is_active=True)
        .order_by("departure_time")
        .all()
    )
    return render(
        request,
        "booking/daytime_trip.html",
        context={
            "direction": direction,
            "direction_slug": direction_slug,
            "date_routes": date_routes,
            "trip_times_all": trip_times_all,
            "trip_times_active": trip_times_active,
        },
    )


class TripCreateView(LoginRequiredMixin, CreateView):
    """Класс для бронирования поездки. LoginRequiredMixin - ограничивает доступ не аутентифицированным пользователям"""

    model = Trip
    form_class = TripModelForm  # либо form_class либо fields
    template_name = "booking/trip.html"

    def get_context_data(self, **kwargs) -> dict:
        """Функция для передачи context в template"""

        context = super().get_context_data(**kwargs)
        direction, day, time = self.get_path_params()
        context["direction"] = direction
        context["day"] = day
        context["time"] = time
        return context

    def get_success_url(self) -> str:
        """URL, на который будет произведено перенаправление"""

        return reverse(
            "booking:trip-success",
            kwargs={
                "direction_slug": self.kwargs["direction_slug"],
                "date_route": self.kwargs["date_route"],
                "timetrip_id": self.kwargs["timetrip_id"],
            },
        )

    def get_path_params(self) -> Any:
        """Функция, предназначенная для получения записей, по параметрам пути"""

        direction_slug = self.kwargs["direction_slug"]
        direction = get_object_or_404(Direction, slug=direction_slug)
        date_routes = direction.dateroute_set.filter(
            is_active=True
        ).all()  # dateroute в dateroute_set взяли из модели
        # Получили список всех поездок сортированных по времени (с утра до вечера)
        date_route = self.kwargs["date_route"]
        day = get_object_or_404(date_routes, date_route=date_route)
        # timetrip в timetrip_set взяли из модели
        timetrip_id = self.kwargs["timetrip_id"]
        trip_times = (
            day.timetrip_set.filter(direction=direction)
            .order_by("departure_time")
            .all()
        )
        time = get_object_or_404(trip_times, id=timetrip_id)

        return direction, day, time

    def form_valid(self, form: Any) -> HttpResponseRedirect:
        """Функция для проверки валидности"""

        direction, day, time = self.get_path_params()

        # Проверка того, имеет ли пользователь запись на данную поездку.
        # Идея такая: 1 пользователь - 1 заказ на данную поездку
        trip = time.trip_set.filter(username=self.request.user)
        if trip:
            return HttpResponseRedirect(
                reverse(
                    "booking:trip-impossible",
                    kwargs={
                        "direction_slug": self.kwargs["direction_slug"],
                        "date_route": self.kwargs["date_route"],
                        "timetrip_id": self.kwargs["timetrip_id"],
                    },
                )
            )

        form.instance.username = self.request.user
        form.instance.date_of_the_trip = day
        form.instance.departure_time = time

        # Необходимо для валидации поля number_of_reserved_places модели Trip. Достаем значение о количестве свободных
        # мест в поездке
        number_of_seats = form.instance.number_of_reserved_places
        number_of_free_seats = time.number_of_free_places_in_trip()

        if number_of_seats > number_of_free_seats:
            form.add_error(
                "number_of_reserved_places",
                f"Свободных мест осталось {number_of_free_seats}",
            )
            return super().form_invalid(form)

        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


@decorator_log
def booking_success(
    request: HttpRequest, direction_slug: str, date_route: datetime, timetrip_id: int
) -> HttpRequest:
    """Функция, предназначенная для перехода к template после успешного бронирования поездки"""

    trip = Trip.objects.get(username=request.user, departure_time=timetrip_id)

    # Генерация html шаблона билета
    template = get_template("ticket.html")
    context = {"trip": trip}
    ticket_template = template.render(context)
    ticket_name = (
        f"{trip.username}_{trip.get_direction()}_{trip.date_of_the_trip}_{trip.departure_time}_"
        f"{datetime.datetime.now()}.pdf"
    )
    # Конвертирование html шаблона в pdf файл
    css_path = os.path.join(os.path.dirname(__file__), "static/css/style_booking.css")
    pdfkit.from_string(ticket_template, f"media/booking/{ticket_name}", css=css_path)

    # Задача в celery
    send_tripticket_task.delay(
        request.user.email, ticket_name, serializers.serialize("json", [trip])
    )

    context = {"ticket_template": ticket_template}
    return render(request, "booking/booking_success.html", context=context)


@decorator_log
def booking_impossible(
    request: HttpRequest, direction_slug: str, date_route: datetime, timetrip_id: int
) -> HttpRequest:
    """Функция, предназначенная для перехода к template в случае, если пользователь бронировал уже данную поездку"""

    return render(request, "booking/booking_impossible.html")


@login_required(login_url="users:login", redirect_field_name="next")
@decorator_log
def trips_history(request):
    """Функция предназначена для перехода к странице с информацией о поездках, которые уже прошли и попали
    в историю поездок пользователя

    Идея такая, что как только день время поездки проходит, т.е с помощью celery становится неактивным, то поездки
    переходит в историю поездок пользователя.
    """

    user_inactive_trips = [
        x
        for x in Trip.objects.filter(username=request.user)
        if not x.departure_time.is_active
    ]

    return render(
        request,
        "booking/user_trip_history.html",
        context={"user_trips": user_inactive_trips},
    )


@login_required(login_url="users:login", redirect_field_name="next")
@decorator_log
def account(request: HttpRequest) -> HttpRequest:
    """Функция предназначена для перехода к странице с контактной информацией и отображением все активных
    поездок пользователя"""

    user_trips = [
        x
        for x in Trip.objects.filter(username=request.user)
        if x.departure_time.is_active
    ]

    return render(request, "booking/account.html", context={"user_trips": user_trips})


@decorator_log
def trip_remove_in_account(request: HttpRequest, trip_id: int) -> HttpResponseRedirect:
    """Функция предназначена для удаления поездки из всех поездок пользователя"""

    trip = Trip.objects.get(username=request.user, id=trip_id)
    trip.delete()

    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@decorator_log
def contacts(request: HttpRequest) -> HttpRequest:
    """Функция предназначена для перехода к странице с контактной информацией"""

    return render(request, "booking/contacts.html")

final_edu_project/travel_service/booking/templates/booking/account.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<body>
    <div class="account">
        <div class="container">
            <div class="account__wrap">
                <div class="account__user">
                    <h3 class="account__title">{{ user.get_full_name }}</h3><br>
                    <p class="account__userinfo">Информация о пользователе</p>
                    <p class="account__userinfo">Username: {{ user.username }}</p>
                    <p class="account__userinfo">Моб. телефон: {{ user.phone }}</p>
                    <p class="account__userinfo">Дата рождения: {{ user.date_of_birth }}</p>
                    <p class="account__userinfo">Email: {{ user.email }}</p>
                    <p class="account__userinfo">Дата регистрации: {{ user.date_joined }}</p>
                    <a class="account__btn-remove" href="{% url 'users:user-info-edit' %}">Изменить</a>
                </div>
            {% if user_trips %}
                <div class="account__info">
                    <h3 class="account__title">Информация о поездках</h3>
                        <table class="account__table-wrap">
                            <tr class="account__table-item">
                                <th class="account__tabletop">Направление</th>
                                <th class="account__tabletop">Дата поездки</th>
                                <th class="account__tabletop">Время отправления</th>
                                <th class="account__tabletop">Время прибытия</th>
                                <th class="account__tabletop">Номер остановки</th>
                                <th class="account__tabletop">Места</th>
                                <th class="account__tabletop">Цена</th>
                            </tr>
                        {% for trip in user_trips %}
                            <tr class="account__table-item">
                                <td class="account__text">{{ trip.get_direction }}</td>
                                <td class="account__text">{{ trip.date_of_the_trip }}</td>
                                <td class="account__text">{{ trip.departure_time }}</td>
                                <td class="account__text">{{ trip.arrival_time_calculation }}</td>
                                <td class="account__text">{{ trip.landing_place }}</td>
                                <td class="account__text">{{ trip.number_of_reserved_places }}</td>
                                <td class="account__text">{{ trip.get_full_price }} BYN</td>
                            </tr>
                            <tr class="account__table-item">
                                <td class="account__text" colspan="6">Информация о перевозчике: {{ trip.car_info_in_trip.name }}, гос.номер {{ trip.car_info_in_trip.auto_number }}, {{ trip.car_info_in_trip.carrier_phone }}</td>
                                <td class="account__text" rowspan="2"><a class="account__btn-remove" href="{% url 'booking:trip_remove' trip.id %}">Отменить поездку</a><td>
                            </tr>
                            <tr class="account__table-item">
                                <td class="account__text" colspan="6">
                                    {% if trip.user_comment %}
                                        Комментарий: {{ trip.user_comment}}
                                    {% else %}
                                        Комментарий: &nbsp;
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                        {% else %}
                    <div class="account__info">
                        <h3 class="account__title">Информация о поездках</h3>
                            <h4 class="account__text-notrip">
                                У вас нет забронированных поездок
                            </h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/booking_impossible.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div class="booking">
        <div class="container">
            <div class="booking__impossible-wrap">
                <p  class="booking__text">Вы уже забронировали поездку на выбранные Вами дату и время.</p>
                <p  class="booking__text">Вы можете увидеть подробную информацию о ней в своем личном кабинете.</p>
            </div>

            <a class="booking__text booking__text-btn" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </div>
    </div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/booking_success.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div class="booking">
        <div class="container">
            <div class="booking__info-wrap">
                <p class="booking__text">Спасибо за бронирование, <span class="booking__text booking__text-green">{{ user.get_full_name }}</span>.</p>
                <p class="booking__text">На указанный email - <span class="booking__text booking__text-green">{{ user.email }}</span> выслан забронированный Вами билет на данную поездку.</p>
            </div>

            {{ ticket_template }}

            <a class="booking__text booking__text-btn" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </div>
    </div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/contacts.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div class="contacts">
        <div class="container">
            <div class="contacts__info">
                <h3 class="contacts__title">Контакты</h3>
                <p class="contacts__text">    Офис: г. Пинск, ул. Костюшко, 23, кв. 25 </p>
                <p class="contacts__text">    Группа Вконтакте: vk.com/bus_by </p>
                <p class="contacts__text">    Инстаграм: @bus_by </p>
                <p class="contacts__text">    Электронная почта: info@busby.by </p>
            </div>
            <div class="contacts__booking">
                <h3 class="contacts__title">Бронирование мест</h3>
                <p class="contacts__text">    a1	+375 44 311-22-13 mts	+375 29 233-55-33 </p>
                <p class="contacts__text">    Диспетчерская работает с 08:00 до 21:00 ежедневно без выходных. Онлайн заказ доступен круглосуточно.
                </p>
            </div>
        </div>
    </div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/daytime_trip.html
{% extends 'base.html' %}

{% block content %}
<body>
    <div class="daytime">
        <div class="container">
            <h2 class="daytime__title">{{ direction }}</h2>
                <h3 class="daytime__date"> Даты: </h3>
                    <div class="daytime__info">
                        {% for date_route in date_routes %}
                            <a class="daytime__date-btn" href="{% url 'booking:direction' direction_slug=direction_slug date_route=date_route.date_route %}">{{ date_route }}</a>
                        {% endfor %}
                    </div>
                <h3 class="daytime__date"> Поездки: </h3>
                {% if trip_times_all %}
                    <table class="daytime__list-wrap">
                        <tr class="daytime__list-item">
                            <th class="daytime__tabletop">Время отправления</th>
                            <th class="daytime__tabletop">Время прибытия</th>
                            <th class="daytime__tabletop">Свободные места</th>
                            <th class="daytime__tabletop">Всего мест</th>
                            <th class="daytime__tabletop">Цена</th>
                            <th class="daytime__tabletop">&nbsp;</th>
                        </tr>
                        {% for trip_time in trip_times_all %}
                        <tr class="daytime__list-item">
                            <td class="daytime__trip">{{ trip_time.departure_time }}</td>
                            <td class="daytime__trip">{{ trip_time.arrival_time_calculation }}</td>
                            <td class="daytime__trip">{{ trip_time.number_of_free_places_in_trip }} </td>
                            <td class="daytime__trip">{{ trip_time.number_of_seats }}</td>
                            <td class="daytime__trip">{{ trip_time.price }} BYN</td>
                            {% if trip_time.number_of_free_places_in_trip %}
                                {% if trip_time in trip_times_active %}
                                    <td><a class="daytime__trip-btn" href="{% url 'booking:trip' direction_slug=direction_slug date_route=trip_time.date_of_the_trip timetrip_id=trip_time.id %}">Забронировать</a></td>
                                {% endif %}
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <h2 class="daytime__title">
                        На выбранную дату поездок нет :(
                    </h2>
                {% endif %}
        </div>
    </div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/index.html
{% extends 'base.html' %}

{% block content %}
<body>
<main>
    <section class="main">
        <div class="container">
            <table class="main__list-wrap">
                <tr class="main__list-item">
                    <th class="main__direction">Направление</th>
                    <th class="main__direction">Время в пути</th>
                    <th class="main__direction">Цена</th>
                    <th class="main__direction">&nbsp</th>
                </tr>
                {% for direction in directions %}
                <tr class="main__list-item">
                    <td class="main__direction">{{ direction.name }}</td>
                    <td class="main__direction">{{ direction.format_travel_time }}</td>
                    <td class="main__direction">от {{ direction.min_price }} BYN</td>
                    <td><a class="main__btn" href="{% url 'booking:direction' direction_slug=direction.slug date_route=today %}">Перейти</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
</main>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/trip.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body>
<div class="booking">
    <div class="container">
      <form class="booking__form" action="" method="post">
          {% csrf_token %}
            <div class="booking__form-wrap">
              <h2 class="booking__title">Бронирование</h2>
                <div class="booking__form-group">
                    <p class="booking__info">  {{ direction }}</p>
                    <p class="booking__info">  {{ day}}</p>
                    <p class="booking__info">  {{ time }}</p>
                    <p class="booking__info">  {{ user.phone }}</p>
                    <p class="booking__info">  {{ user.get_full_name }}</p>
                </div>
                <div class="booking__form-group">
                  {% for field in form %}
                    <h3 class="booking__text"> {{ field.label_tag }}</h3>
                    {{ field }}
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  {% endfor %}
                    <input class="booking__form-btn" type="submit" value="Забронировать">
              </div>
            </div>
      </form>
    </div>
</div>
</body>

{% endblock  %}

final_edu_project/travel_service/booking/templates/booking/user_trip_history.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<body>
    <div class="account">
        <div class="container">
            <div class="account__wrap">
                {% if user_trips %}
                    <div class="account__info">
                        <h3 class="account__title">Информация о завершенных поездках</h3>
                            <table class="account__table-wrap">
                                <tr class="account__table-item">
                                    <th class="account__tabletop">Направление</th>
                                    <th class="account__tabletop">Дата поездки</th>
                                    <th class="account__tabletop">Время отправления</th>
                                    <th class="account__tabletop">Время прибытия</th>
                                    <th class="account__tabletop">Номер остановки</th>
                                    <th class="account__tabletop">Места</th>
                                    <th class="account__tabletop">Цена</th>
                                </tr>
                            {% for trip in user_trips %}
                                <tr class="account__table-item">
                                    <td class="account__text">{{ trip.get_direction }}</td>
                                    <td class="account__text">{{ trip.date_of_the_trip }}</td>
                                    <td class="account__text">{{ trip.departure_time }}</td>
                                    <td class="account__text">{{ trip.arrival_time_calculation }}</td>
                                    <td class="account__text">{{ trip.landing_place }}</td>
                                    <td class="account__text">{{ trip.number_of_reserved_places }}</td>
                                    <td class="account__text">{{ trip.get_full_price }} BYN</td>
                                </tr>
                                <tr class="account__table-item">
                                    <td class="account__text" colspan="6">Информация о перевозчике: {{ trip.car_info_in_trip.name }}, гос.номер {{ trip.car_info_in_trip.auto_number }}, {{ trip.car_info_in_trip.carrier_phone }}</td>
                                </tr>
                                <tr class="account__table-item">
                                    <td class="account__text" colspan="6">
                                        {% if trip.user_comment %}
                                            Комментарий: {{ trip.user_comment}}
                                        {% else %}
                                            Комментарий: &nbsp;
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                {% else %}
                        <div class="account__info">
                            <h3 class="account__title">Информация о завершенных поездках</h3>
                                <h4 class="account__text-notrip">
                                    У вас нет еще ни одной завершенной поездки!
                                </h4>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</body>

{% endblock  %}