final_edu_project/travel_service/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Travel Service API",
        default_version="v1",
        description="Travel Service where you can booking one or several places in different directories, "
        "dates and time.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@busby.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("directions/", views.GetDirectionInfoView.as_view()),
    path("dateroutes/", views.GetDateRouteInfoView.as_view()),
    path("timetrips/", views.GetTimeTripInfoView.as_view()),
    path(
        "info/<slug:direction_slug>/<date_route>/",
        views.DirectionDateRouteView.as_view(),
    ),
    path("filter-timetrips/", views.GetTimeTripInfoFilterView.as_view()),
    path("search-timetrips/", views.GetTimeTripInfoSearchView.as_view()),
    path("order-timetrips/", views.GetTimeTripInfoOrderView.as_view()),
]

final_edu_project/travel_service/booking/urls.py
from django.urls import path

from . import views

app_name = "booking"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "<slug:direction_slug>/<date_route>/", views.get_daytime_trip, name="direction"
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/success",
        views.booking_success,
        name="trip-success",
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/impossible",
        views.booking_impossible,
        name="trip-impossible",
    ),
    path(
        "<slug:direction_slug>/<date_route>/<int:timetrip_id>/",
        views.TripCreateView.as_view(),
        name="trip",
    ),
    path("contacts", views.contacts, name="contacts"),
    path(
        "account/trip/remove/<int:trip_id>/",
        views.trip_remove_in_account,
        name="trip_remove",
    ),
    path("account", views.account, name="account"),
    path("history", views.trips_history, name="trips-history"),
]

final_edu_project/travel_service/travel_service/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_edu_project/travel_service/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import forms, views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            next_page="booking:index", template_name="users/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="booking:index"),
        name="logout",
    ),
    path(
        "change-pass/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy(
                "users:password_change_done"
            ),  # Куда буду перенаправлен после успешной смены пароля,
            # можно перенаправить и на главную страницу. Указан стандартный, переопределил из-за app_name = 'users'.
            template_name="users/password_change.html",  # шаблон, использующейся для отображения
            form_class=forms.CustomPasswordChangeForm,
        ),  # форма, которая передается в шаблон
        name="change",
    ),
    path(
        "change-pass-confirm/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_success.html"
        ),
        name="password_change_done",
    ),
    path(
        "password-reset",
        auth_views.PasswordResetView.as_view(
            email_template_name="users/password_reset_mail.html",
            template_name="users/password_reset.html",
            success_url=reverse_lazy("users:pass-reset-done"),
        ),
        name="pass-reset",
    ),
    path(
        "password-reset-done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="pass-reset-done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("users:reset_complete"),
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="reset_complete",
    ),
    path("info-edit", views.user_edit, name="user-info-edit"),
]

final_edu_project/travel_service/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/style_booking.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <title>Travel service</title>
  </head>
</html>

{% include 'header.html' %}

{% block content %}

{% endblock content %}

{% include 'footer.html' %}

final_edu_project/travel_service/templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <div class="footer_contacts">
            <a class="footer_contacts-link" href="https://www.instagram.com/"><img src="{% static 'instagram.svg' %}"></a>
            <a class="footer_contacts-link" href="https://vk.com/"><img src="{% static 'vk.svg' %}"></a>
            <a class="footer_contacts-link" href="https://mail.yandex.ru/"><img src="{% static 'yandex.svg' %}"></a>
        </div>
        <div class="footer__wrap">
            <p class="footer__text">Copyright © 2023 Travel booking service. All Rights Reserved
                Made with by Pavel Zolotov</p>
        </div>
    </div>
</footer>

final_edu_project/travel_service/templates/header.html
{% load static %}
<header class="header">
    <div class="container">
        <div class="header__wrap">
            <div class="header__logotype">
                <a class="header__logotype-btn" href="{% url 'booking:index' %}">
                    <img class="header__logotype-img" src="{% static 'logo.png' %}" alt="BusBY"></a>
            </div>
            <div class="header__contacts">
                <a class="header__contacts-btn" href="{% url 'booking:account' %}">Личный кабинет</a>
                <a class="header__contacts-btn" href="{% url 'booking:contacts' %}">Контакты</a>
            </div>
            <div class="header__user">
                {% if user.is_authenticated %}
                <p class="greeting__text">Приветствуем, <span class="greeting__text greeting__text-span">{{ user.first_name }} {{ user.last_name }}</span>.
                    Спасибо, что вошли на сервис! </p>
                <div class="user__wrapper user__wrapper-top">
                    <a class="user__btn-top" href="{% url 'users:logout' %}">Выйти</a>
                    <a class="user__btn-top" href="{% url 'users:change' %}">Сменить пароль</a>
                </div>
                {% else %}
                <p class="greeting__text">Приветствуем, нового пользователя. Пожалуйста, войдите на сервис.</p>
                <div class="user__wrapper user__wrapper-top">
                    <a class="user__btn-top" href="{% url 'users:register' %}">Регистрация</a>
                    <a class="user__btn-top" href="{% url 'users:login' %}">Войти</a>
                </div>
                {% endif %}
            </div>
        </div>
   </div>
</header>

final_edu_project/travel_service/templates/ticket.html
<head>
    <meta charset="UTF-8" />
</head>
<body>
    <div class="ticket">
        <div class="ticket__header">
            <h3>Билет</h3>
        </div>
      <div class="ticket__body">
        <div class="ticket__section">
            <h3>Информация о поездке</h3>
            <p>Пассажир: {{ trip.get_full_name }}</p>
            <p>Направление: {{ trip.get_direction }}</p>
            <p>Дата: {{ trip.date_of_the_trip }}</p>
            <p>Время отправления: {{ trip.departure_time }}</p>
            <p>Время прибытия: {{ trip.arrival_time_calculation }}</p>
            <p>Кол-во мест: {{ trip.number_of_reserved_places }}</p>
            <p>Остановка: {{ trip.landing_place }}</p>
        </div>
        <div class="ticket__section">
            <h3>Информация о перевозчике: </h3>
            <p>{{ trip.car_info_in_trip.name }}</p>
            <p>гос.номер {{ trip.car_info_in_trip.auto_number }}</p>
            <p>{{ trip.car_info_in_trip.carrier_phone }}</p>
        </div>
        <div class="ticket__section">
            {% if trip.user_comment %}
                <h3>Комментарий:</h3>
                <p>{{ trip.user_comment }}</p>
            {% else %}
                <h3>Комментарий: &nbsp;</h3>
            {% endif %}
        </div>
      </div>
      <div class="ticket__footer">
        <p>Итого: <span>{{ trip.get_full_price }} BYN</span></p>
      </div>
    </div>
</body>