final_edu_project/travel_service/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Travel Service API",
        default_version="v1",
        description="Travel Service where you can booking one or several places in different directories, "
        "dates and time.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@busby.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("directions/", views.GetDirectionInfoView.as_view()),
    path("dateroutes/", views.GetDateRouteInfoView.as_view()),
    path("timetrips/", views.GetTimeTripInfoView.as_view()),
    path(
        "info/<slug:direction_slug>/<date_route>/",
        views.DirectionDateRouteView.as_view(),
    ),
    path("filter-timetrips/", views.GetTimeTripInfoFilterView.as_view()),
    path("search-timetrips/", views.GetTimeTripInfoSearchView.as_view()),
    path("order-timetrips/", views.GetTimeTripInfoOrderView.as_view()),
]

final_edu_project/travel_service/travel_service/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include("api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_edu_project/travel_service/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import forms, views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            next_page="booking:index", template_name="users/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="booking:index"),
        name="logout",
    ),
    path(
        "change-pass/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy(
                "users:password_change_done"
            ),  # Куда буду перенаправлен после успешной смены пароля,
            # можно перенаправить и на главную страницу. Указан стандартный, переопределил из-за app_name = 'users'.
            template_name="users/password_change.html",  # шаблон, использующейся для отображения
            form_class=forms.CustomPasswordChangeForm,
        ),  # форма, которая передается в шаблон
        name="change",
    ),
    path(
        "change-pass-confirm/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_success.html"
        ),
        name="password_change_done",
    ),
    path(
        "password-reset",
        auth_views.PasswordResetView.as_view(
            email_template_name="users/password_reset_mail.html",
            template_name="users/password_reset.html",
            success_url=reverse_lazy("users:pass-reset-done"),
        ),
        name="pass-reset",
    ),
    path(
        "password-reset-done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="pass-reset-done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("users:reset_complete"),
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="reset_complete",
    ),
    path("info-edit", views.user_edit, name="user-info-edit"),
]

final_edu_project/travel_service/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class BookingUser(AbstractUser):
    """Пользовательский класс User, необходимый для расширения возможностей базового User"""

    phone = PhoneNumberField(null=True)
    date_of_birth = models.DateField(verbose_name="Date of birth", null=True)
    cookie_consent = models.BooleanField(
        default=True, verbose_name="Do you agree to the use of cookies?"
    )
    email = models.EmailField(
        unique=True, verbose_name="Email address", null=True, blank=True
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_full_name(self) -> str:
        """Возвращает first_name и last_name с пробелом между ними."""

        return "%s %s" % (self.first_name, self.last_name)

final_edu_project/travel_service/users/forms.py
from django import forms
from django.contrib.auth.forms import (PasswordChangeForm, UserChangeForm,
                                       UserCreationForm)
from django.forms import SelectDateWidget, ValidationError
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import BookingUser


class CustomUserFieldsMixinFrom(forms.Form):
    """Класс Mixin, для повторяющихся полей пользователя, от которого затем наследуются классы с формами"""

    phone = PhoneNumberField(
        label="Номер телефона",
        region="BY",
        widget=PhoneNumberPrefixWidget(
            attrs={"class": "form__input"},
            country_choices=[("BY", "375"), ("RU", "7"), ("UA", "380")],
        ),
    )
    username = forms.CharField(
        label="Логин", widget=forms.TextInput(attrs={"class": "form__input"})
    )
    first_name = forms.CharField(
        label="Имя", widget=forms.TextInput(attrs={"class": "form__input"})
    )
    last_name = forms.CharField(
        label="Фамилия", widget=forms.TextInput(attrs={"class": "form__input"})
    )
    email = forms.EmailField(
        label="Email", widget=forms.EmailInput(attrs={"class": "form__input"})
    )
    cookie_consent = forms.BooleanField(
        label="Вы соглашаетесь с размещением файлов cookie на вашем компьютере, "
        "с целью анализа использования Веб-сайта?",
        initial=1,
        widget=forms.CheckboxInput(attrs={"class": "form__input form__input-check"}),
    )


class CustomUserCreationForm(UserCreationForm, CustomUserFieldsMixinFrom):
    """Класс для создания формы по регистрации пользователя"""

    date_of_birth = forms.DateField(
        label="Дата рождения",
        widget=SelectDateWidget(
            years=range(1940, 2010), attrs={"class": "form__input"}
        ),
    )
    password1 = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form__input"})
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"class": "form__input"}),
    )

    class Meta(UserCreationForm.Meta):
        """Добавляем доп. поле"""

        model = BookingUser
        fields = (
            "phone",
            "username",
            "first_name",
            "last_name",
            "email",
            "date_of_birth",
            "password1",
            "password2",
            "cookie_consent",
        )


class CustomPasswordChangeForm(PasswordChangeForm):
    """Класс для создания формы по смене пароля"""

    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.PasswordInput(attrs={"class": "form__input"}),
    )
    new_password1 = forms.CharField(
        label="Новый пароль", widget=forms.PasswordInput(attrs={"class": "form__input"})
    )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"class": "form__input"}),
    )

    def clean(self) -> None:
        """Функция для проверки несовпадения нового пароля и старого"""
        cleaned_data = super().clean()
        user = self.user
        new = cleaned_data.get("new_password1")
        if user.check_password(new):
            raise ValidationError("Новый пароль совпадает со старым.")


class CustomUserUpdateForm(UserChangeForm, CustomUserFieldsMixinFrom):
    """Класс для создания формы по редактированию информации пользователя"""

    password = None  # для того чтобы убрать отображение поля password в форме

    class Meta(UserCreationForm.Meta):
        """Добавляем доп. поле"""

        model = BookingUser
        fields = (
            "phone",
            "username",
            "first_name",
            "last_name",
            "email",
            "cookie_consent",
        )
        exclude = ("password",)

final_edu_project/travel_service/users/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import CustomUserCreationForm, CustomUserUpdateForm


def register(request: HttpRequest) -> HttpRequest:
    """Функция для регистрации пользователя"""

    if request.method == "GET":
        return render(request, "users/register.html", {"form": CustomUserCreationForm})
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend="django.contrib.auth.backends.ModelBackend")
            return redirect(reverse("booking:index"))
        else:
            form = CustomUserCreationForm(request.POST)
        return render(request, "users/register.html", {"form": form})


@login_required(login_url="users:login", redirect_field_name="next")
def user_edit(request: HttpRequest) -> HttpRequest:
    """Функция предназначена для перехода к странице для редактирования контактной информацией"""

    if request.method == "POST":
        form = CustomUserUpdateForm(request.POST, instance=request.user)
        print(form)
        if form.is_valid():
            form.save()
            return redirect(reverse("booking:account"))
    else:
        form = CustomUserUpdateForm(instance=request.user)
    return render(
        request,
        "users/user_info_edit.html",
        context={"form": form},
    )

final_edu_project/travel_service/users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Login</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Войти</h2>
              {% for f in form %}
            <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
            <div class="form__error">{{ f.errors }}</div>
            {% endfor %}
            <input class="form__btn" type="submit" value="Sign In">

            {% load socialaccount %}
            {% get_providers as socialaccount_providers %}

            {% for provider in socialaccount_providers %}
                {% if provider.id == "openid" %}
                    {% for brand in provider.get_brands %}
                      <a title="{{brand.name}}" class="{{provider.id}} {{brand.id}}" href="{% provider_login_url provider.id openid=brand.openid_url process=process %}">{{brand.name}}</a>
                    {% endfor %}
                {% endif %}
                <a class="form__link" title="{{provider.name}}" class="{{provider.id}}" href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">{{provider.name}}</a>
            {% endfor %}
            <br>

            <a class="form__link" href="{% url 'users:pass-reset' %}">Забыли пароль?</a>
            <a class="form__link" href="{% url 'users:register' %}">Регистрация</a>
            <a class="form__link" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </form>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_change.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Change Password</title>
</head>
<body>
<section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Смена пароля</h2>
          {% for f in form %}
            <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
            <div class="form__error">{{ f.errors }}</div>
          {% endfor %}
            <input class="form__btn" type="submit" value="Поменять">
              <a class="form__link" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </form>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_change_success.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Title</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <div class="form__wrap">
          <div class="form__image">
            <img class="form__image-png" src="{% static 'changed_ok.png' %}" alt="Success" />
          </div>
          <a class="form__link" href="{% url 'users:login' %}">Войти</a>
        </div>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_reset.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Password Reset</title>
</head>
<body>
<section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Запросить смену пароля</h2>
              <div class="form__wrap-text">
              <p class="form__text">На указанный email мы вышлем письмо со ссылкой доступа в Ваш личный кабинет.</p>
                <p class="form__text">Перейдите по ссылке и задайте новый пароль для входа в систему</p>
                <p class="form__text">Введите адрес электронной почты, куда будет выслано письмо для смены пароля</p>
              </div>>
          {% for f in form %}
            <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
            <div class="form__error">{{ f.errors }}</div>
          {% endfor %}
            <input class="form__btn" type="submit" value="Отправить">
              <a class="form__link" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </form>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_reset_complete.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Password reset complete</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <div class="form__wrap">
          <h3 class="form__title">Вы успешно сменили пароль</h3>
          <a class="form__link" href="{% url 'users:login' %}">Вернуться на страницу для входа</a>
        </div>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_reset_confirm.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Confirm password reset</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Установите новый пароль</h2>
              {% for f in form %}
                <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
                <div class="form__error">{{ f.errors }}</div>
              {% endfor %}
            <input class="form__btn" type="submit" value="Установить">
        </form>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_reset_done.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Password Reset Done</title>
</head>
<body>
<section class="form">
      <div class="container">
        <div class="form__wrap">
          <h3 class="form__title">Проверьте указанный вами email.</h3>
          <a class="form__link" href="{% url 'users:login' %}">Вернуться на страницу для входа</a>
        </div>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/password_reset_mail.html
Здравствуйте, {{ user }}!
Вы сделали запрос на восстановление пароля для сайта busby.by.

Если вы не делали такого запроса, пожалуйста, не отвечайте на данное сообщение.

Для установки нового пароля для сайта перейдите, пожалуйста, по ссылке:

{{ protocol}}://127.0.0.1:8000/{% url 'users:password_reset_confirm' uidb64=uid token=token %}

С уважением, команда BusBY.

final_edu_project/travel_service/users/templates/users/register.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Register</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Регистрация пользователя</h2>
              {% for f in form %}
                <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
                <div class="form__error">{{ f.errors }}</div>
              {% endfor %}
            <input class="form__btn" type="submit" value="Зарегистрироваться">
            <a class="form__link" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </form>
      </div>
    </section>
</body>
</html>

final_edu_project/travel_service/users/templates/users/user_info_edit.html
<!DOCTYPE html>
{% load static %}
<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap/js/css/bootstrap.min.js' %}"></script>
<html lang="en">
  <head>
    <meta charset="UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--подключение стилей-->
    <link rel="stylesheet" href="{% static "css/form.css" %}" />

    <!--подключение шрифтов-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&family=Raleway:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />
    <title>Register</title>
</head>
<body>
    <section class="form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form__wrapper">
            <h2 class="form__title">Редактировать информацию о пользователе</h2>
              {% for f in form %}
                <div class="form__wrap-input" ><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</div>
                <div class="form__error">{{ f.errors }}</div>
              {% endfor %}
            <input class="form__btn" type="submit" value="Редактировать">
            <a class="form__link" href="{% url 'booking:index' %}">Вернуться на главную страницу</a>
        </form>
      </div>
    </section>
</body>
</html>